---
title: "Final Project"
author: "Audrey Ling Huen Wong"
date: "12/6/2021"
output: html_document
---
## Load and Filter Data

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(dplyr)
storms <- read_csv("data/StormEvents_details-ftp_v1.0_d2020_c20211019.csv")
problems(storms)
```

```{r filter data}
table(storms$STATE)
storms_new <- filter(storms, storms$STATE !="PUERTO RICO", storms$STATE !="GUAM") %>% 
  select(STATE, MONTH_NAME,EVENT_TYPE, CZ_NAME, BEGIN_DATE_TIME, END_DATE_TIME, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGE_PROPERTY, DAMAGE_CROPS, MAGNITUDE, MAGNITUDE_TYPE, EPISODE_NARRATIVE,BEGIN_DAY, BEGIN_TIME, END_YEARMONTH, END_DAY, END_TIME)
```


## Exploring Variables Plots

```{r states}
# Which states have the most storms in the US？
storms_new  %>%
  group_by(STATE) %>%
  summarise(count=n()) %>%
  ggplot() + geom_col(aes(STATE,count)) + theme(axis.text.x = element_text(angle = 90))

(big_storms <- storms_new %>%
  count(STATE, name = "total_number_of_storms") %>%
  arrange(desc(total_number_of_storms)) %>%
  top_n(5))
```

```{r regions}
# Which regions have the most storms in the US？
regions <- read_csv("data/us_census_bureau_regions_and_divisions.csv")
regions <- regions %>%
  select(State, Region)
regions$State = toupper(regions$State)
storms_new <- storms_new %>%
  rename(State = STATE)
storms_new$State = toupper(storms_new$State)

storms_region %>%
  group_by(Region) %>%
  summarise(count=n()) %>%
  ggplot() + geom_col(aes(Region,count))
```

```{r months}
# What months have the most storms?
storms_new  %>%
  group_by(MONTH_NAME) %>%
  summarise(count=n()) %>%
  ggplot() + geom_col(aes(MONTH_NAME,count)) + theme(axis.text.x = element_text(angle = 90))

(big_months <- storms_new %>%
  count(MONTH_NAME, name = "total_number_of_storms") %>%
  arrange(desc(total_number_of_storms)) %>%
  top_n(5))
```

```{r types}
# What are the most common types of storms?
storms_new  %>%
  group_by(EVENT_TYPE) %>%
  summarise(count=n()) %>%
  ggplot() + geom_col(aes(EVENT_TYPE,count)) + theme(axis.text.x = element_text(angle = 90))
```

```{r death}
# What are the number of injuries and deaths during storms by state?
#Find number of injuries and deaths in storms?
injureDeathDf <- storms_region %>%
  mutate(injuriesDeaths = INJURIES_DIRECT + INJURIES_INDIRECT + DEATHS_DIRECT + DEATHS_INDIRECT)
#plot injuries & deaths per region per event type
(regionInjureDeaths <- injureDeathDf %>%
  select(EVENT_TYPE, Region, injuriesDeaths) %>%
  group_by(Region, EVENT_TYPE) %>%
  ggplot() + geom_point(aes(EVENT_TYPE,injuriesDeaths, color = Region)) + stat_summary(aes(x = EVENT_TYPE, y = injuriesDeaths), fun = mean, fun.min = min, fun.max = max, geom = "crossbar", color = "grey") + theme(axis.text.x = element_text(angle = 90)))

```

```{r damage}
# Damage property among states?

```


## Prediction Models
Prediction of each type of storm in different regions 

```{r prediction}

```






